[build-system]
requires = [
        'numpy',
        'matplotlib',
        'datetime',
        'empyrical',
        'quantstats',
        'yfinance',
        'ipython',
        'fpdf',
        'pyportfolioopt'

    ]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
